// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/v1/asset.proto

package protov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BigInt with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BigInt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BigInt with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BigIntMultiError, or nil if none found.
func (m *BigInt) ValidateAll() error {
	return m.validate(true)
}

func (m *BigInt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return BigIntMultiError(errors)
	}

	return nil
}

// BigIntMultiError is an error wrapping multiple validation errors returned by
// BigInt.ValidateAll() if the designated constraints aren't met.
type BigIntMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BigIntMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BigIntMultiError) AllErrors() []error { return m }

// BigIntValidationError is the validation error returned by BigInt.Validate if
// the designated constraints aren't met.
type BigIntValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BigIntValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BigIntValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BigIntValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BigIntValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BigIntValidationError) ErrorName() string { return "BigIntValidationError" }

// Error satisfies the builtin error interface
func (e BigIntValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBigInt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BigIntValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BigIntValidationError{}

// Validate checks the field values on Asset with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Asset) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Asset with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AssetMultiError, or nil if none found.
func (m *Asset) ValidateAll() error {
	return m.validate(true)
}

func (m *Asset) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AssetValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AssetValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AssetValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetChainId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AssetValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AssetValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChainId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AssetValidationError{
				field:  "ChainId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AssetMultiError(errors)
	}

	return nil
}

// AssetMultiError is an error wrapping multiple validation errors returned by
// Asset.ValidateAll() if the designated constraints aren't met.
type AssetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssetMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssetMultiError) AllErrors() []error { return m }

// AssetValidationError is the validation error returned by Asset.Validate if
// the designated constraints aren't met.
type AssetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssetValidationError) ErrorName() string { return "AssetValidationError" }

// Error satisfies the builtin error interface
func (e AssetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAsset.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssetValidationError{}

// Validate checks the field values on Stake with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Stake) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Stake with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in StakeMultiError, or nil if none found.
func (m *Stake) ValidateAll() error {
	return m.validate(true)
}

func (m *Stake) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StakeValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StakeValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StakeValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetChainId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StakeValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StakeValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChainId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StakeValidationError{
				field:  "ChainId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StakeMultiError(errors)
	}

	return nil
}

// StakeMultiError is an error wrapping multiple validation errors returned by
// Stake.ValidateAll() if the designated constraints aren't met.
type StakeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StakeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StakeMultiError) AllErrors() []error { return m }

// StakeValidationError is the validation error returned by Stake.Validate if
// the designated constraints aren't met.
type StakeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StakeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StakeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StakeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StakeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StakeValidationError) ErrorName() string { return "StakeValidationError" }

// Error satisfies the builtin error interface
func (e StakeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStake.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StakeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StakeValidationError{}

// Validate checks the field values on Loan with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Loan) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Loan with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LoanMultiError, or nil if none found.
func (m *Loan) ValidateAll() error {
	return m.validate(true)
}

func (m *Loan) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Asset

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LoanValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LoanValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LoanValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Address

	if all {
		switch v := interface{}(m.GetChainId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LoanValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LoanValidationError{
					field:  "ChainId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChainId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LoanValidationError{
				field:  "ChainId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LoanMultiError(errors)
	}

	return nil
}

// LoanMultiError is an error wrapping multiple validation errors returned by
// Loan.ValidateAll() if the designated constraints aren't met.
type LoanMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoanMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoanMultiError) AllErrors() []error { return m }

// LoanValidationError is the validation error returned by Loan.Validate if the
// designated constraints aren't met.
type LoanValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoanValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoanValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoanValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoanValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoanValidationError) ErrorName() string { return "LoanValidationError" }

// Error satisfies the builtin error interface
func (e LoanValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoan.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoanValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoanValidationError{}

// Validate checks the field values on ExtraData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExtraData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExtraData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExtraDataMultiError, or nil
// if none found.
func (m *ExtraData) ValidateAll() error {
	return m.validate(true)
}

func (m *ExtraData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPartiallyFillable()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExtraDataValidationError{
					field:  "PartiallyFillable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExtraDataValidationError{
					field:  "PartiallyFillable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPartiallyFillable()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExtraDataValidationError{
				field:  "PartiallyFillable",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExtraDataMultiError(errors)
	}

	return nil
}

// ExtraDataMultiError is an error wrapping multiple validation errors returned
// by ExtraData.ValidateAll() if the designated constraints aren't met.
type ExtraDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtraDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtraDataMultiError) AllErrors() []error { return m }

// ExtraDataValidationError is the validation error returned by
// ExtraData.Validate if the designated constraints aren't met.
type ExtraDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtraDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtraDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtraDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtraDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtraDataValidationError) ErrorName() string { return "ExtraDataValidationError" }

// Error satisfies the builtin error interface
func (e ExtraDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtraData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtraDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtraDataValidationError{}

// Validate checks the field values on Intent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Intent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Intent with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in IntentMultiError, or nil if none found.
func (m *Intent) ValidateAll() error {
	return m.validate(true)
}

func (m *Intent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExtraData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "ExtraData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "ExtraData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExtraData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IntentValidationError{
				field:  "ExtraData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IntentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetExpirationAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "ExpirationAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IntentValidationError{
					field:  "ExpirationAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpirationAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IntentValidationError{
				field:  "ExpirationAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch v := m.From.(type) {
	case *Intent_FromAsset:
		if v == nil {
			err := IntentValidationError{
				field:  "From",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFromAsset()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromAsset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromAsset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFromAsset()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "FromAsset",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Intent_FromStake:
		if v == nil {
			err := IntentValidationError{
				field:  "From",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFromStake()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromStake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromStake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFromStake()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "FromStake",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Intent_FromLoan:
		if v == nil {
			err := IntentValidationError{
				field:  "From",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFromLoan()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromLoan",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "FromLoan",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFromLoan()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "FromLoan",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	switch v := m.To.(type) {
	case *Intent_ToAsset:
		if v == nil {
			err := IntentValidationError{
				field:  "To",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToAsset()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToAsset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToAsset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToAsset()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "ToAsset",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Intent_ToStake:
		if v == nil {
			err := IntentValidationError{
				field:  "To",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToStake()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToStake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToStake",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToStake()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "ToStake",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Intent_ToLoan:
		if v == nil {
			err := IntentValidationError{
				field:  "To",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToLoan()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToLoan",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IntentValidationError{
						field:  "ToLoan",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToLoan()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IntentValidationError{
					field:  "ToLoan",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if m.Recipient != nil {
		// no validation rules for Recipient
	}

	if len(errors) > 0 {
		return IntentMultiError(errors)
	}

	return nil
}

// IntentMultiError is an error wrapping multiple validation errors returned by
// Intent.ValidateAll() if the designated constraints aren't met.
type IntentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntentMultiError) AllErrors() []error { return m }

// IntentValidationError is the validation error returned by Intent.Validate if
// the designated constraints aren't met.
type IntentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntentValidationError) ErrorName() string { return "IntentValidationError" }

// Error satisfies the builtin error interface
func (e IntentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntentValidationError{}

// Validate checks the field values on Body with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Body) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Body with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BodyMultiError, or nil if none found.
func (m *Body) ValidateAll() error {
	return m.validate(true)
}

func (m *Body) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetIntents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BodyValidationError{
						field:  fmt.Sprintf("Intents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BodyValidationError{
						field:  fmt.Sprintf("Intents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BodyValidationError{
					field:  fmt.Sprintf("Intents[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BodyMultiError(errors)
	}

	return nil
}

// BodyMultiError is an error wrapping multiple validation errors returned by
// Body.ValidateAll() if the designated constraints aren't met.
type BodyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BodyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BodyMultiError) AllErrors() []error { return m }

// BodyValidationError is the validation error returned by Body.Validate if the
// designated constraints aren't met.
type BodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BodyValidationError) ErrorName() string { return "BodyValidationError" }

// Error satisfies the builtin error interface
func (e BodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BodyValidationError{}
